services:
  vire-server:
    image: ghcr.io/bobmcallan/vire-server:latest
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.scope=vire"

  watchtower:
    image: containrrr/watchtower
    container_name: vire-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=120
      - WATCHTOWER_SCOPE=vire
    labels:
      - "com.centurylinklabs.watchtower.scope=vire"
    restart: unless-stopped
